### ISSUE TITLE
outputCachePointers overrides method from class

### ISSUE THREAD

**Issue by jeffreyjackson** [forcedotcom/SalesforceMobileSDK-iOS#1058]
Just passing this back for your review.

```
ld: warning: instance method 'outputCachePointers' in category from 

Build/Products/Debug-iphonesimulator/libPods-SalesforceMobileSDK-iOS.a(CSFNetwork+Caching.o) 

overrides method from class in

Build/Products/Debug-iphonesimulator/libPods-SalesforceMobileSDK-iOS.a(CSFNetwork.o)
```

**Comment by akhileshgupta** [comment]
@wmathurin can you take a look at this?

**Comment by jeffreyjackson** [comment]
@akhileshgupta @wmathurin do you all need any additional information for this?

**Comment by jeffreyjackson** [comment]
It seems this error shows up when building for armv7, or simulator.

**Comment by bhariharan** [comment]
We have fixed this in our ```unstable``` branch. This will be in our next release.

**Comment by brad36** [comment]
Do you mean next release after 3.3.1? I'm still seeing this issue in 3.3.1

**Comment by bhariharan** [comment]
@brad36 Yes - the one after ```3.3.1``` (next major release).

**Comment by brad36** [comment]
Ok thanks

**Comment by B82607** [comment]
Still having this issue with 4.0.1. I tried clean, and deleting derived data. 

`ld: warning: instance method 'outputCachePointers' in category from /Users/andy/Documents/Projects/Contracts/Contracts2/Dependencies/SalesforceNetwork/libSalesforceNetwork.a(CSFNetwork+Caching.o) overrides method from class in /Users/andy/Documents/Projects/Contracts/Contracts2/Dependencies/SalesforceNetwork/libSalesforceNetwork.a(CSFNetwork.o)`
