### ISSUE TITLE
Issue login after logout

### ISSUE THREAD

**Issue by tiendnuit** [forcedotcom/SalesforceMobileSDK-iOS#1066]
I'm building SmartSync app with lastest Salesforce sdk version 3.2. I have problem when I logout user, after that I login again with same user and I get this error: "Credentials missing for user..."
Let me know if more details are needed, or if there are any suggestions. Thanks!

**Comment by bhariharan** [comment]
@tiendnuit Are you able to repro this issue on ```3.2.1```. We released a patch with some bug fixes recently.

**Comment by tiendnuit** [comment]
Yes, I still get error with new released 3.2.1. After check in code, I see that SFSmartStore didn't update user's credentials.

**Comment by bhariharan** [comment]
@tiendnuit We have a fix for ```SmartStore``` not getting wiped in our upcoming release [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1076). Feel free to reopen this if you're still seeing the issue after applying that fix.
