### ISSUE TITLE
Unable to import SalesforceMobileSDK_iOS

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/SalesforceMobileSDK-iOS#1292]
rev tested against:
------------
 88d6716033f4a35226546b765c2cb5e3cfb58c48
Branch: 
-----------
unstable

Related Issues:
-----------
#1251 

Symptom:
-----------
Using `import SalesforceMobileSDK_iOS` in swift fails to build

Errors:
----------
    include of non-modular header inside framework module 'SalesforceMobileSDK_iOS.SalesforceSDKCore'
    #import <SalesforceSDKCore/NSData+SFAdditions.h>
    include of non-modular header inside framework module 'SalesforceMobileSDK_iOS.SalesforceSDKCore'
    #import <SalesforceSDKCore/NSData+SFSDKUtils.h>

...

Expected Behavior:
-----------
- Import should succeed

Actual Behavior:
-----------
- Import fails

Work arounds:
-----------
- Use a bridging header
 - Not desired behavior because this pulls the contents of the header in to all swift files in the project extending compilation time

**Comment by wmathurin** [comment]
A possible workaround might be to add the following at the end of your podfile
```shell
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
```

**Comment by mgetzbw** [comment]
I'll try that on Monday and add it to the list of workarounds if it does,
long term however a proper fix is probably the best course as I'd rather
not affect other pods

On Friday, December 11, 2015, Wolfgang Mathurin <notifications@github.com>
wrote:

> A possible workaround might be to add the following at the end of your
> podfile
>
> post_install do |installer|
>   installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
>     configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
>   end
> end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1292#issuecomment-164096271>
> .
>


-- 

------------------------------

*Michael Getz <http://www.bluewolf.com/people/michael-getz>* ─ Developer II
─ Bluewolf ─ O: 720 263 2988

→ Download Bluewolf’s Annual The State of Salesforce Report
<http://bit.ly/Zsb1xZ>

**Comment by mgetzbw** [comment]
@wmathurin doesn't seem to work as of XCode 7.2, cocoapods sets it on the pod automatically, but setting it on the main project seems to have no effect

**Comment by doovers** [comment]
I'm having the same issue...

    Include of non-modular header inside framework module SalesforceMobileSDK_iOS.SFUserAccount_SalesforceNetwork'
    Include of non-modular header inside framework module 'SalesforceMobileSDK_iOS.SalesforceNetwork'

**Comment by mgetzbw** [comment]
@doovers This should have been fixed with pull #1303 by @wmathurin I just haven't had a chance to check that it's fixed yet

**Comment by doovers** [comment]
@mgetzbw I just updated my podfile to use the latest commit and I'm still having the same issue.

**Comment by wmathurin** [comment]
In 4.0 we have support for use_frameworks but you need to use the pod specs
from our specs repo.

Your pod file should look something like:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/build/app_template_files/__NativeSwiftTemplateAppName__/Podfile

To see it in action, npm install forceios and then run forceios create and
choose native_swift for the app type then look try the generated
application.

**Comment by davidmdavis** [comment]
I used forceios to create a native Swift application. When I import SmartStore, I'm still getting the following error(s):

````
/workspace/SalesforceSwiftTest/SalesforceSwiftTest/RootViewController.swift:27:8: Could not build Objective-C module 'SmartStore'
````
````
/workspace/SalesforceSwiftTest/Pods/SmartStore/libs/SmartStore/SmartStore/Classes/sqlite/SqliteAdditions.h:26:9: Include of non-modular header inside framework module 'SmartStore.SqliteAdditions'
````

**Comment by kgrigsby59** [comment]
@davidmdavis I was able to import SmartStore after removing SqliteAdditions.h from SmartStore.h and SmartStore-umbrella.h

**Comment by DarkRockman** [comment]
@davidmdavis I tried your workaround but I'm not able to import SmartStore, anyhow, this should not be the proper fix for this, so how can we import SmartStore without using the bridging-header workaround as stated by @mgetzbw  ?

**Comment by wmathurin** [comment]
We just released 4.0.2 and those issues should be resolved.
Please upgrade forceios and let us know if you are still getting errors.

**Comment by mgetzbw** [comment]
@wmathurin non-modular includes is still occurring in 4.0.2 in two specific spots `SFRestRequest.h` and `SFRestAPISalesforceAction.h` this blocks us using the libraries in an internal cocoapod
