### ISSUE TITLE
Crash: SFRootViewManager Application tried to present modally an active controller

### ISSUE THREAD

**Issue by eescamilla** [forcedotcom/SalesforceMobileSDK-iOS#1494]
We use Crashlytics/Fabric for crash tracking and we received this message: 

Fatal Exception: NSInvalidArgumentException
Application tried to present modally an active controller <CBILoadScreenViewController: 0x17d4b660>.

It occurred isnide of SFRootViewManager specific here for version 4.0 : SFRootViewManager.m line 91
__40-[SFRootViewManager pushViewController:]_block_invoke

Went back in history to see if this was a previous issue but didn't see anything related to this, one more thing to note is that all of the crashes I have seen are coming from iOS 9.3.1 iPad 4th generation, thanks.

**Comment by kchitalia** [comment]
@eescamilla Can we get more detailed logs? Can you try to reproduce this on the sample app in the Mobile SDK.

**Comment by hiralnaik** [comment]
Hi

Here is the logs for same crash. @kchitalia We are seeing this crash multiple times a day. 

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x2424db0b __exceptionPreprocess
1  libobjc.A.dylib                0x23a0adff objc_exception_throw
2  UIKit                          0x28b9e5a3 -[UIViewController _presentViewController:withAnimationController:completion:]
3  UIKit                          0x28ba085d __62-[UIViewController presentViewController:animated:completion:]_block_invoke_2
4  UIKit                          0x2883a275 +[UIView(Animation) performWithoutAnimation:]
5  UIKit                          0x28ba07a1 __62-[UIViewController presentViewController:animated:completion:]_block_invoke
6  UIKit                          0x28ba0a89 -[UIViewController _performCoordinatedPresentOrDismiss:animated:]
7  UIKit                          0x289256cf -[UIViewController presentViewController:animated:completion:]
8  XXXXX                          0x289479 __40-[SFRootViewManager pushViewController:]_block_invoke (SFRootViewManager.m:91)
9  libdispatch.dylib              0x23ddfcbf _dispatch_call_block_and_release
10 libdispatch.dylib              0x23ddfcab _dispatch_client_callout
11 libdispatch.dylib              0x23de4559 _dispatch_main_queue_callback_4CF
12 CoreFoundation                 0x2420f755 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x2420dc4f __CFRunLoopRun
14 CoreFoundation                 0x2415c1c9 CFRunLoopRunSpecific
15 CoreFoundation                 0x2415bfbd CFRunLoopRunInMode
16 GraphicsServices               0x25778af9 GSEventRunModal
17 UIKit                          0x28894435 UIApplicationMain
18 XXXXX                          0x167237 main (main.m:40)
19 libdispatch.dylib              0x23e08873 (Missing)

Thanks
Hiral Naik

**Comment by kchitalia** [comment]
You are seeing this crash on the sample apps in the Mobile SDK repo on github, or is this on your app that uses the Mobile SDK?

@huminzhi Have you seen this before.

**Comment by hiralnaik** [comment]
@kchitalia  I didn't check on the sample apps in the Mobile SDK repo on github. This is happening in the our apps. We have multiple apps and we are seeing same crash.

**Comment by bhariharan** [comment]
@hiralnaik Please try our sample apps and let us know the repro steps in our sample apps.

**Comment by mattlacey** [comment]
I've not been able to reproduce this myself, but I can see it's happening with some of our end-users via Crashlytics as well. Same line.

**Comment by hiralnaik** [comment]
@bhariharan  @kchitalia I am seeing many errors with sample apps so I was unable to test in sample apps. 

I investigated very deeply in our apps and I was able to reproduce this crash.
Below are the steps to follow.
1. Launch the app
2. When you see the launch screen, enter your app into background mode.
3. When your app come back to foreground mode, call logout "[[SFAuthenticationManager sharedManager] logout];" 
4. Your app will crash with Application tried to present modally an active controller

Make sure your delegate method - (void)authManagerDidFinishAuthWebViewLoad:(SFAuthenticationManager *)manager not start executing.

So view controller instance is trying to call line 91 presentViewController in SFRootViewManager twice. So first call will work fine, but second call will cause you crash.

I hope this will help.

Thanks
Hiral

**Comment by MishchanchukA** [comment]
I have the same issue but with other steps to reproduce:
1. Start app, go to the login screen
2. Open Settings
3. Change host
4. Quickly reproduce steps 2-3. Sometimes need to reproduce this steps few times to get a crash.

**Comment by SumitKr88** [comment]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <PKFUINavigationController: 0x12d0db400>.'

Last Exception Backtrace:
0   CoreFoundation                       0x0000000181946db0 __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x0000000180fabf80 objc_exception_throw + 52
2   UIKit                                0x0000000186e1efb4 -[UIViewController _presentViewController:withAnimationController:completion:] + 4992
3   UIKit                                0x0000000186e215d0 __62-[UIViewController presentViewController:animated:completion:]_block_invoke_2 + 64
4   UIKit                                0x0000000186aab5b4 +[UIView(Animation) performWithoutAnimation:] + 76
5   UIKit                                0x0000000186e21540 __62-[UIViewController presentViewController:animated:completion:]_block_invoke + 308
6   UIKit                                0x0000000186e21890 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 468
7   UIKit                                0x0000000186b973cc -[UIViewController presentViewController:animated:completion:] + 180
8   xxxxxAPPNAME                         0x0000000100690e00 __40-[SFRootViewManager pushViewController:]_block_invoke + 348
9   libdispatch.dylib                    0x00000001813914bc _dispatch_call_block_and_release + 20
10  libdispatch.dylib                    0x000000018139147c _dispatch_client_callout + 12
11  libdispatch.dylib                    0x0000000181396b84 _dispatch_main_queue_callback_4CF + 1840
12  CoreFoundation                       0x00000001818fcd50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
13  CoreFoundation                       0x00000001818fabb8 __CFRunLoopRun + 1624
14  CoreFoundation                       0x0000000181824c50 CFRunLoopRunSpecific + 380
15  GraphicsServices                     0x000000018310c088 GSEventRunModal + 176
16  UIKit                                0x0000000186b06088 UIApplicationMain + 200
17  xxxxAPPNAME                         0x00000001000ff724 main (main.m:33)
18  ???                                  0x00000001813c28b8 0x0 + 0

Having this crash quite often, but not sure of the steps to reproduce.
Can you please suggest on this? Thoughts?

Thanks & Regards,
Sumit Kumar

**Comment by shwetachitlangia** [comment]
@kchitalia @bhariharan @huminzhi Any update as to when this issue will be resolved?

**Comment by hiralnaik** [comment]
I was able to solve this issue in our code. Try to avoid `[[SFAuthenticationManager` sharedManager] logout];` (logout) call multiple time. I mean when one logout call is in progress don't make another logout call. I used to get 3 to 4 crashes a day but now since 1 month, we have only 1 crash related to this.

**Comment by kchitalia** [comment]
@hiralnaik @eescamilla We have done some enhancements and fixes around this in our 4.2 release. Can you please get the latest from the master branch and see if this issue still exists?

**Comment by kchitalia** [comment]
@hiralnaik @eescamilla Please reopen this issue if it still exists in the latest 4.2 release of the mobile SDK.

**Comment by Annelies1** [comment]
I still have this crash in version 4.3 
Last Exception Backtrace:
1	CoreFoundation	__exceptionPreprocess + 124
2	libobjc.A.dylib	objc_exception_throw + 52
3	UIKit	-[UIViewController _presentViewController:withAnimationController:completion:] + 4880
4	UIKit	__62-[UIViewController presentViewController:animated:completion:]_block_invoke_2 + 64
5	UIKit	+[UIView(Animation) performWithoutAnimation:] + 100
6	UIKit	__62-[UIViewController presentViewController:animated:completion:]_block_invoke + 308
7	UIKit	-[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 520
8	UIKit	-[UIViewController presentViewController:animated:completion:] + 180
9	PocketRetail	__40-[SFRootViewManager pushViewController:]_block_invoke + 556
10	libdispatch.dylib	_dispatch_call_block_and_release + 20
11	libdispatch.dylib	_dispatch_client_callout + 12
12	libdispatch.dylib	_dispatch_main_queue_callback_4CF + 996
13	CoreFoundation	__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
14	CoreFoundation	__CFRunLoopRun + 1656
15	CoreFoundation	CFRunLoopRunSpecific + 440
16	GraphicsServices	GSEventRunModal + 176
17	UIKit	-[UIApplication _run] + 680
18	UIKit	UIApplicationMain + 204
19	PocketRetail	main (main.m:33)
20	???	0x0 + 0

**Comment by bhariharan** [comment]
@Annelies1 Please let us know if you can reproduce this with the latest Mobile SDK version from our `unstable` branch.

**Comment by Annelies1** [comment]
We only see the crash in production, not in our test environment. I only see the crash in HockeyApp, the users don't tell me the reproduction steps. Do you know reproduction steps? Then I can check with your branch.

**Comment by bhariharan** [comment]
@Annelies1 We can not reproduce this since `Mobile SDK 4.2`. It was fixed a while ago.

**Comment by SumitKr88** [comment]
Hi @bhariharan @kchitalia  , we have updated our SDK to 5.0
but we can still see this crash happening, occurrence of this is quite high.

Can you please help us with your suggestion and views on this. 

Many Thanks,
Sumit Kumar
