### ISSUE TITLE
Credentials missing for user after logging out and logging in

### ISSUE THREAD

**Issue by davidmdavis** [forcedotcom/SalesforceMobileSDK-iOS#1906]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10.1.1
4. Device: iPad Pro
5. Steps to reproduce:
````
// Logout
SFAuthenticationManager.shared().logout()

// Login again
SFAuthenticationManager.shared().login(completion: success, failure: failure)
````
6. Actual behavior: Values are missing (i.e. null) in the SFUserAccount credentials after logging out and logging back in as the same user. This seems to occur randomly and not after every logout/login. 
7. Expected Behavior: Values should be populated, organizationId specifically.
8. Error Log:

Some values have been removed for security, but there are a lot of null values in SFOAuthCredentials for a SFUserAccount after logging out and logging back in.

````
2017-01-31 09:06:14.877226 DBUMobileApp[751:238432] Credentials missing for user <SFUserAccount username=user@test.com fullName=Test User accessScopes={(
    web,
    api
)} credentials=<SFOAuthKeychainCredentials: 0x1701511a0, identifier="identifier" clientId="clientId" domain="test.salesforce.com" identityUrl="(null)" instanceUrl="(null)" communityId="(null)" communityUrl="(null)" issuedAt="(null)" organizationId="(null)" protocol="https" redirectUri="redirectUri">, community=(null)>
````

**Comment by davidmdavis** [comment]
Any updates on this issue? Have you been able to reproduce?

**Comment by quoctc** [comment]
Me too, 

WARNING com.salesforce <SFDirectoryManager>: Credentials missing for user <SFUserAccount username=<<my user name>> fullName=<<my full name>>> accessScopes={(
    web,
    api
)} credentials=<SFOAuthKeychainCredentials: 0x60000014be70, identifier="3AAG9dPGzpc3kWyfsTrGaQCTa63Q8bWGQz66k4pTy5mOeTB6mqCWyrvVl8Mdnyo1Lwwuqlq74ImU3XmEaD3Gl-1344030212" clientId="3AGG9dPGzpc3kWyfsTrGaQCTa63Q8bWGQz66k4pTy5mPeTB6mqCWyrvVl8Mdnyo1Lwwuqlq74ImU3XmEaU3Pl" domain="example.salesforce.com" identityUrl="(null)" instanceUrl="(null)" communityId="(null)" communityUrl="(null)" issuedAt="(null)" organizationId="(null)" protocol="https" redirectUri="<<my>>://login/success">, community=(null)>

**Comment by quoctc** [comment]
Hi, I debugged and know what the problem is. please fix it.
The problem is the stored user in this class: SFSmartStoreDatabaseManager does not reload after logged out and logged in. I see because you are using the singleton pattern for this class. After I terminate app and reopen, the singleton will be re-init will new stored user.

**Comment by quoctc** [comment]
Fixed by call this function when I clear database: clearSharedStoreMemoryState. this function does not public, I must add it to the category. Please fixed in next update.

**Comment by trooper2013** [comment]
@davidmdavis  logout() and login(..) are all asynchronous operations. It is quite possible that an  attempt to login is made while logout is in progress. To protect against this situation, you should add a delegate(SFAuthenticationManagerDelegate)  to SFAuthenticationManager you will be notified when the logout is complete.

**Comment by bhariharan** [comment]
We have fixed this in our `5.1` release.

**Comment by davidmdavis** [comment]
I'm still seeing this issue after updating to version 5.1. Are there any steps I need to take?

**Comment by bhariharan** [comment]
In `5.1` the app is expected to explicitly set `currentUser` when logout or login occurs. Are you able to reproduce this issue on any of our sample apps? If not, I recommend mimicking the patterns established there for handling `credentials` in your app as well.

**Comment by fr33kill** [comment]
@davidmdavis - Did you able to set currentUser explicitly? If yes, how did you set it?

**Comment by streamofones** [comment]
For posterity, here's the logout flow based on @bhariharan's recommendation:

`let userAccount: SFUserAccount = SFUserAccountManager.sharedInstance().currentUser!
SFUserAccountManager.sharedInstance().logoutUser(userAccount)`

However, the issue is still happening with the latest version. Soups are not cleared, and upon re-login using the same user, outputs "Credentials missing for user".

**Comment by MoinJanjua** [comment]
This might be late but I faced the same issue. Make sure that you are not missing the bootconfig.json file in your project directory. If the file is missing add the file to[![enter image description here][1]][1] your project and rebuild it. Hope this helps.
![Screenshot 2021-04-06 at 4 47 25 PM](https://user-images.githubusercontent.com/52666065/113706733-77bf1780-96f8-11eb-8dae-f426c3074acf.png)
