### ISSUE TITLE
App crashing   when we try to pass other than string values like boolean,dictionary or array in an query param of SFRestMethodPOST

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#2065]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App:Native
3. OS Version:iOS 10.3
4. Device:iPad Air simulator
5. Steps to reproduce:
Try to send request like below
NSDictionary *params = @{@"paramName" : array/dictionary,
                             @"paramName" : @YES/IntergerValue
                             };

SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:@"/services/apexrest/someCustomAPI/Webservicename" queryParams:params];

The app is crashing in latest SDK 5.1 but working fine in SDK 4.x 
6. Actual behavior: The app is crashing
7. Expected Behavior:The app should not crash
8. Error Log:
[__NSArrayI stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x6180008549a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111a8cb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000110fe9141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111afc134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000111a13840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000111a133b8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x000000010a9d5fc7 -[__NSConcreteURLComponents setQueryItems:] + 573
	6   360ONE                              0x000000010963857b -[SFRestRequest prepareRequestForSend] + 2555
	7   360ONE                              0x00000001096327ae -[SFRestAPI enqueueRequest:delegate:] + 110
	8   360ONE                              0x0000000109632220 -[SFRestAPI send:delegate:] + 1344
	9   360ONE                              0x000000010962d170 -[SFRestAPI(Blocks) sendRESTRequest:failBlock:completeBlock:] + 256
	12  Foundation                          0x000000010a9e16f7 -[__NSOperationInternal _start:] + 627
	13  Foundation                          0x000000010a9dd47c __NSOQSchedule_f + 198
	14  libdispatch.dylib                   0x000000011264c05c _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000011262a94f _dispatch_queue_serial_drain + 221
	16  libdispatch.dylib                   0x000000011262b669 _dispatch_queue_invoke + 1084
	17  libdispatch.dylib                   0x000000011262dec4 _dispatch_root_queue_drain + 634
	18  libdispatch.dylib                   0x000000011262dbef _dispatch_worker_thread3 + 123
	19  libsystem_pthread.dylib             0x0000000112a8b616 _pthread_wqthread + 1299
	20  libsystem_pthread.dylib             0x0000000112a8b0f1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by bhariharan** [comment]
@SrinivasGit049 We changed the underlying network stack in `5.1`, which requires some minor tweaks to requests. In this case you need to change your request code from:
`SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:@"/services/apexrest/someCustomAPI/Webservicename" queryParams:params];`
to:
```
SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:@"/services/apexrest/someCustomAPI/Webservicename" queryParams:nil];
[request setCustomRequestBodyDictionary:params contentType:@"application/json"];
```
Basically, `queryParams` should be `nil` for a `POST` and the body should be explicitly set on the `request` object. Let me know if that works.

**Comment by SrinivasGit049** [comment]
Thank you this worked for me!

**Comment by puckdevteam** [comment]
Hi @bhariharan 
After updating to 5.1, we got the same issue but your solution doesn't work for us. 

We have two different cases:

1. **GET request with parameters**

`SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodGET path:path queryParams:parameters];`

Exception:
_[__NSCFNumber stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x78772160
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x78772160'_


2. **Post request with parameters and file data**

We were using:
```
SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:completePath queryParams:parameters];    
[request addPostFileData:data paramName:@"fileData" fileName:name mimeType:mimeType];
```

Since this method [request addPostFileData:data paramName:@"fileData" fileName:name mimeType:mimeType]; has changed, we tried:

```
SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:completePath queryParams:parameters];
[request addPostFileData:data
                 description:@"fileData"
                    fileName:name
                    mimeType:mimeType];

```
This one gives us an error:
_Error Domain=NSURLErrorDomain Code=-1017 "cannot parse response" UserInfo={NSErrorFailingURLStringKey=xxxxxxxxxxxxxxx, _kCFStreamErrorCodeKey=-1, NSErrorFailingURLKey=xxxxxxxxxxxxxxx, NSLocalizedDescription=cannot parse response, _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x7e039e20 {Error Domain=kCFErrorDomainCFNetwork Code=-1017 "(null)" UserInfo={_kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-1}}}_


We also tried:

```
    SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:completePath queryParams:nil];
    [request setCustomRequestBodyDictionary:parameters contentType:@"application/json"];
    [request addPostFileData:data
                 description:@"fileData"
                    fileName:name
                    mimeType:mimeType];
```
We got:
_Error Domain=NSURLErrorDomain Code=-1017 "cannot parse response" UserInfo={NSErrorFailingURLStringKey= xxxxxxxxxxxxxxx, _kCFStreamErrorCodeKey=-1, NSErrorFailingURLKey= xxxxxxxxxxxxxxx, NSLocalizedDescription=cannot parse response, _kCFStreamErrorDomainKey=4, NSUnderlyingError=0x7e9c2860 {Error Domain=kCFErrorDomainCFNetwork Code=-1017 "(null)" UserInfo={_kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-1}}}_


Any suggestion to keep the same we had working before updating?

**Comment by bhariharan** [comment]
Issue (1) is fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2081) and will be a part of `Mobile SDK 5.2` (or you could cherry-pick the fix in your copy of `Mobile SDK`).

For the files issue, please take a look at our upload API [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestAPI%2BFiles.m#L119) on how to upload. However, the error you're getting is that the response can't be parsed, which means the request was made. Could you set breakpoints in the code and print the response received from the server?

**Comment by puckdevteam** [comment]
Issue 1 is still crashing after applying that fix, because it is not taking into consideration that parameters can come not being an NSString.  


Regarding the second one, I tried using:
```
  SFRestRequest *request = [[SFRestAPI sharedInstance] requestForUploadFile:data
                                                                         name:name
                                                                  description:@"fileData"
                                                                     mimeType:mimeType];
    [[SFRestAPI sharedInstance] sendRESTRequest:request failBlock:^(NSError *error) {
        completion (nil, error);
    } completeBlock:^(id response) {
        completion (response, nil);
    }];


```

That returns the same NSError.
The response is:
```
<NSHTTPURLResponse: 0x7b2277b0> { URL: XXXXXXXX/v39.0/connect/communities/XXXXXXXX/files/users/me } { status code: 411, headers {
    Connection = Close;
    "Content-Length" = 1884;
    "Content-Type" = "text/html";
    Date = "Thu, 29 Jun 2017 17:02:11 GMT";
    Server = scl;
} }

<NSHTTPURLResponse: 0x7a6e9d20> { URL: XXXXXXXX/v39.0/connect/files/users/me } { status code: 411, headers {
    Connection = Close;
    "Content-Length" = 1884;
    "Content-Type" = "text/html";
    Date = "Thu, 29 Jun 2017 17:06:02 GMT";
    Server = scl;
} }
```

Could it be that the request doesn't have the Content-Length header?

**Comment by bhariharan** [comment]
@puckdevteam Regarding issue (1), could you give me an example of a `GET` where the parameters are not a string? Since there is no body for `GET`, I'm not aware of any `Salesforce` APIs that take non-string parameters for `GET`.

Regarding issue (2), you're right. Please add the `Content-Length` header like [this](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2032/files#diff-35a56e65397647b946a932da4d4d35ecR98) for now. This should automatically be added in our next release - I have fixed it [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2032).

**Comment by puckdevteam** [comment]
@bhariharan you're right about GET requests, but I meant that we were sending some parameters to the SDK which are not NSString, for examples NSNumber. 
In any case, we agree that It is an issue we must fix in our side, being sure we don't send non NSString parameters for GET requests.

Thank you for your help.
