### ISSUE TITLE
MobileSdk 7.1.0 does not work with phonegap-plugin-push plugin

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-iOS#2913]
Please fill out the following details:

1. Version of Mobile SDK Used: 
Mobile Sdk 7.1.0
2. Issue found in Native App or Hybrid App:
Hybrid App
3. OS Version: iOS 12.1, 
4. Device: iPhone 6s, 7, 8
5. Steps to reproduce:
After updating the app to Mobile Sdk 7.1.0 I am unable to built the app 
The built is failing while installing phonegap-plugin-push plugin.
6. Actual behavior:
Unable to  built the app
7. Expected Behavior:
App Should built correctly
8. Error Log:
installing "phonegap-plugin-push" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
     Cloning into '/var/folders/_5/c3w8vp6j7wlctnk7msmc6h480000gp/T/d20190619-15135-1cxupbs'...
     warning: Could not find remote branch {s.version} to clone.
     fatal: Remote branch {s.version} not found in upstream origin
[!] `<PBXResourcesBuildPhase UUID=`1D60588D0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `7846C82D02624BE8A771DC70` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

We use this plugin for push notifications. Mobile Sdk version 7.0 works perfectly fine with this plugin.

I like to ask you do we actually need this plugin with 7.1.0? removing this plugin will built the app but push notification no longer works.

is there any other plugin or workaround for push notifications? Please suggest

**Comment by wmathurin** [comment]
We are not seeing the issue here. What version of the cordova cli are you using?

**Comment by Jas05** [comment]
@wmathurin  I am using Cordova 9.0 I also tried with Cordova 8.1.2

**Comment by wmathurin** [comment]
There was an issue with 7.1.0 - that's why we published 7.1.1 an hour later and deprecated 7.1.0.
Since then we published 7.1.2.
I recommend you uninstall 7.1.0 and install 7.1.2, and try again.

**Comment by wmathurin** [comment]
Please re-open if you can repro the issue in the latest version of the Mobile SDK.

**Comment by Jas05** [comment]
@wmathurin as you suggested I tried v7.1.2 but I am still having the same problem, can you please look into this?

Installing "phonegap-plugin-push" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
     Cloning into '/var/folders/_5/c3w8vp6j7wlctnk7msmc6h480000gp/T/d20190722-20156-lve4lw'...
     warning: Could not find remote branch {s.version} to clone.

     fatal: Remote branch {s.version} not found in upstream origin

[!] `<PBXResourcesBuildPhase UUID=`1D60588D0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `5ACEE33C08054DF9B5D266D7` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] The platform of the target `app` (iOS 9.0) may not be compatible with `Cordova (5.1.0)` which has a minimum requirement of iOS 11.0.
[!] The platform of the target `app` (iOS 9.0) may not be compatible with `SalesforceAnalytics (7.1.2)` which has a minimum requirement of iOS 11.0.
